### PR TITLE
Version update. TBB path change.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@greenc-FNAL

**Comment by gartung** [comment]
@knoepfel

**Review by knoepfel — COMMENTED** [review]
These changes look good, @gartung.  The only adjustment I might make is to maybe raise an exception (with a suitable message) if all of the `os.path.exists(self.spec["tbb"].prefix....)` checks fail.  I'm not sure, though, how well exceptions are handled in the context of a Spack installation.

**Comment by gartung** [comment]
Package has a direct dependence on `tbb` so the build should fail if `tbb` is not installed. The `tbb` virtual points to `intel-oneapi-tbb` by default.

**Comment by knoepfel** [comment]
Sure, I understand that.  The subdirectories containing the tbb libraries, though, sometimes have different names (hence the various `if` statements).  And if we missed one of the options, it'd be good to have a simple error message.  I don't insist on any change here, though.

**Review by knoepfel — APPROVED** [review]

**Pull request merged**
